name: 'GitHub Actions OpenTelemetry Exporter'
description: 'Export GitHub Actions workflow runs as OpenTelemetry traces'
author: 'Grafana'

branding:
    icon: 'activity'
    color: 'orange'

inputs:
    github-token:
        description: 'GitHub token for API access'
        required: true
    trace-files-glob:
        description: 'Glob pattern for local JSONL trace files to include in export'
        required: false

runs:
    using: 'node20'
    main: 'dist/index.js'
