name: Bump version
description: Updates version
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  metricsWriteAPIKey:
    description: Grafana Cloud metrics api key
    required: false
  version_call:
    description: Version number invoked from workflow
  precommit_make_target:
    required: false
    description: Make target to execute before the changes are committed for the PR
runs:
  using: 'node20'
  main: 'index.js'
