name: Remove milestone
description: Remove any open issues and pull requests from the current milestone
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions.
    default: ${{ github.token }}
  version_call:
    description: Version number invoked from workflow    
runs:
  using: 'node20'
  main: 'index.js'
