name: Remove milestone
description: Remove any open issues from the current milestone
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions.
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'index.js'
