name: Enterprise check
description: Check if an Enterprise branch exist for the OSS PR check, else create it
inputs:
  token:
    description: GitHub token with branch read/write permissions
    default: ${{ github.token }}
  source_branch:
    description: Source branch of the OSS PR
    required: true
  target_branch:
    description: Target branch of the OSS PR
  pr_number:
    description: OSS PR number
  source_sha:
    description: the HEAD of the OSS PR
runs:
  using: 'node20'
  main: 'index.js'
