name: Update changelog
description: Update changelog
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  metricsWriteAPIKey:
    description: Grafana Cloud metrics api key
    required: false
  grafanabotForumKey:
    description: API key so Grot can publish changelog to community.grafana.com
    required: false
  version_call:
    description: Version number invoked from workflow
runs:
  using: 'node20'
  main: 'index.js'
