"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.writeDocsFiles = void 0;
const fs_1 = __importDefault(require("fs"));
async function writeDocsFiles({ version, builder }) {
    const notes = await builder.buildReleaseNotes({ useDocsHeader: true });
    const title = builder.getTitle();
    const content = `+++
title = "${title}"
[_build]
list = false
+++

<!-- Auto generated by update changelog github action -->

${notes}
		`;
    const releaseNotesDocsPath = `./docs/sources/release-notes`;
    const filePath = `release-notes-${version.replace(/\./g, '-')}.md`;
    const fullPath = `${releaseNotesDocsPath}/${filePath}`;
    fs_1.default.writeFileSync(fullPath, content, { encoding: 'utf-8' });
}
exports.writeDocsFiles = writeDocsFiles;
//# sourceMappingURL=writeDocsFiles.js.map