import { ReleaseNotesBuilder } from './ReleaseNotesBuilder'
import fs from 'fs'

interface DocsReleaseNotesWriterOptions {
	version: string
	builder: ReleaseNotesBuilder
}

export function writeDocsFiles({ version, builder }: DocsReleaseNotesWriterOptions) {
	const notes = builder.buildReleaseNotes({ useDocsHeader: true })
	const title = builder.getTitle()

	const content = `+++
title = "${title}"
[_build]
list = false
+++

<!-- Auto generated by update changelog github action -->

${notes}
		`
	const releaseNotesDocsPath = `./docs/sources/release-notes`
	const filePath = `release-notes-${version.replace(/\./g, '-')}.md`
	const fullPath = `${releaseNotesDocsPath}/${filePath}`

	fs.writeFileSync(fullPath, content, { encoding: 'utf-8' })
}
