name: Backport
description: Automatically creates a cherry pick PR
inputs:
  token:
    description: |
      GitHub token with read and write permissions for issues, comments, and labels.

      Additionally, the token needs read permissions for organization members. 
    default: ${{ github.token }}
  title:
    description: Title for the backport PR
    default: "[Backport to {{base}}] {{originalTitle}}"
  labelsToAdd:
    description: Comma separated list of labels to add to the backport PR.
    required: false
  metricsWriteAPIKey:
    description: Grfanaa Cloud metrics api key
    required: false
runs:
  using: 'node20'
  main: 'index.js'
