name: DocsTarget
description: Extract the version from the given branch
inputs:
  ref_name:
    description: Branch or tag name to extract from
    default: ${{ github.ref_name }}
  trim_prefixes:
    description: Colon `:` separated list of prefixes to be trimmed from references
    default: 'release-:v'
outputs:
  target:
    description: Website documentation version for the given reference
runs:
  using: 'node16'
  main: 'index.js'
