name: GitHub release
description: Creates and updates GitHub releases
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  metricsWriteAPIKey:
    description: Grafana Cloud metrics api key
    required: false
runs:
  using: 'node20'
  main: 'index.js'
