name: actionlint
description: Lint GitHub Actions workflow files using rhysd/actionlint
inputs:
  args:
    description: Arguments to pass to actionlint
    default: ''
runs:
  using: docker
  image: docker://rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
  args:
    - ${{ inputs.args }}
