name: Crowdin create tasks

on:
    workflow_call:
        inputs:
            crowdin_project_id:
                description: 'The Crowdin project ID'
                required: true
                type: number
            crowdin_token:
                description: 'Crowdin API token with access to the Crowdin project, used to create tasks in Crowdin.'
                required: true
                type: string

jobs:
    create-tasks-in-crowdin:
        runs-on: ubuntu-x64

        permissions:
            contents: read
            id-token: write # needed to get vault secrets

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  repository: 'grafana/grafana-github-actions'
                  persist-credentials: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - run: yarn install --immutable --check-cache

            - name: Create tasks
              env:
                  CROWDIN_PROJECT_ID: ${{ inputs.crowdin_project_id }}
                  CROWDIN_PERSONAL_TOKEN: ${{ inputs.crowdin_token }}
              run: node --experimental-strip-types ./.github/workflows/scripts/crowdin/create-tasks.ts
