name: test-otel-export-workflow.yml
on:
    push:
        branches:
            - main
            - grambbledook/grafana-build-example
jobs:
    build:
        runs-on: ubuntu-x64-small
        permissions:
            id-token: write
            contents: read
        env:
            # GitHub context variables for span/trace id calculation
            GITHUB_REPO: ${{ github.repository }}
            GITHUB_RUN_ID: ${{ github.run_id }}
            GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
            GITHUB_JOB_NAME: ${{ github.job }}

            # GOCACHE configuration - shared across all relevant steps
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  repository: 'grafana/grafana'
                  ref: grambbledook/test-toolexec-instrumentation
                  persist-credentials: false

            - name: Install go-toolexec-otel-exporter
              env:
                  GOTOE_VERSION: 'v0.1.4-otel-exporter5'
                  GOTOE_OS: 'linux-amd64'
                  GOTOE_HASH: 'ba1683605d60599f0f4ef3d7698ff546b092c74b7910eeb0614c916ea024f339'
                  GITHUB_STEP_NAME: Run integration tests
              run: |
                  set -xeuo pipefail
                  curl -LO "https://github.com/grafana/go-cache-plugin/releases/download/$GOTOE_VERSION/go-toolexec-otel-exporter-$GOTOE_OS"
                  mv "go-toolexec-otel-exporter-$GOTOE_OS" go-toolexec-otel-exporter
                  echo -e "$GOTOE_HASH\tgo-toolexec-otel-exporter" | sha256sum --check
                  chmod +x go-toolexec-otel-exporter
                  file go-toolexec-otel-exporter
                  sudo mv go-toolexec-otel-exporter /bin/go-toolexec-otel-exporter # move to PATH

            - name: Setup Go
              uses: actions/setup-go@v6.0.0
              with:
                  go-version-file: go.mod
                  cache: true

            - name: Get Vault secrets
              id: vault-secrets
              uses: grafana/shared-workflows/actions/get-vault-secrets@main
              with:
                  repo_secrets: |
                      OTEL_EXPORTER_OTLP_API_KEY=grafana-otlp-api-key:api-key-base64

            - name: Build Grafana With ToolExec
              continue-on-error: true
              env:
                  OTEL_EXPORTER_OTLP_HEADERS: 'Authorization=Basic ${{ env.OTEL_EXPORTER_OTLP_API_KEY }}'
                  GITHUB_STEP_NAME: Build Grafana With ToolExec
              run: |
                  TOOLEXEC_PATH=go-toolexec-otel-exporter  make build-go

            - name: Test Grafana With ToolExec
              continue-on-error: true
              env:
                  OTEL_EXPORTER_OTLP_HEADERS: 'Authorization=Basic ${{ env.OTEL_EXPORTER_OTLP_API_KEY }}'
                  GITHUB_STEP_NAME: Build Grafana With ToolExec
              run: |
                  go test -toolexec="go-toolexec-otel-exporter" .../.

            - name: Cleanup
              run: |
                  kill $(cat go-cache-plugin.pid)
