name: Test

on: pull_request

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v6
              with:
                  node-version-file: .nvmrc
                  cache: yarn

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build yarn
              run: yarn run build

            - name: Git checkout
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "ERROR: Please run *yarn build* and commit your changes.";
                    git diff --exit-code
                  fi

            - name: Run tests
              run: yarn run test
